apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: student5
  name: student5-deployment
spec:
  selector:
    matchLabels:
      app: student5
  template:
    metadata:
      labels:
        app: student5
    spec:
      containers:
      - name: student5
        image: registry.tanzu.dk/ops2devops/student5:v1
