apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentx-deployment
  namespace: student5
spec:
  selector:
    matchLabels:
      app: student5
  template:
    metadata:
      labels:
        app: student5
    spec:
      containers:
      - name: student5
        image: registry.tanzu.dk/ops2devops/student5:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student5
spec:
  type: NodePort
  selector:
    app: student5
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30015 # Remember to change to student number.

